# Generated by Django 4.1.5 on 2023-02-21 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0002_alter_customerprofile_user'),
        ('quotationapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerapp.customerprofile'),
        ),
    ]
