# Generated by Django 4.1.5 on 2023-02-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadcsv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('Bihar', 'Bihar'), ('Jharkhand', 'Jharkhand'), ('West Bengal', 'West Bengal')], max_length=50)),
                ('gender', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('csf_file', models.FileField(blank=True, upload_to='csvdata')),
            ],
        ),
    ]
